# Generated by Django 5.2.8 on 2025-12-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='imagen',
            field=models.ImageField(upload_to='ptarjetas_fotos'),
        ),
    ]
