# Generated by Django 5.2.8 on 2025-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_alter_tarjeta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta_Fauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='tarjetas_fauna_fotos')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='tarjetas_flora_fotos')),
                ('nativa', models.BooleanField(default=False)),
                ('toxica', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
