# Generated by Django 5.2.8 on 2025-12-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0004_tarjeta_fauna_tarjeta_flora_delete_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta_fauna',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarjeta_flora',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
