# Generated by Django 5.2.8 on 2025-12-04 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_categoria_fauna_diega_categoria_fauna_dieta'),
        ('tarjetas', '0005_alter_tarjeta_fauna_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_fauna',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tarjeta_flora',
            name='nativa',
        ),
        migrations.RemoveField(
            model_name='tarjeta_flora',
            name='toxica',
        ),
        migrations.AddField(
            model_name='tarjeta_fauna',
            name='categoria_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_fauna_clase'),
        ),
        migrations.AddField(
            model_name='tarjeta_fauna',
            name='categoria_dieta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_fauna_dieta'),
        ),
        migrations.AddField(
            model_name='tarjeta_fauna',
            name='categoria_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_flora_origen'),
        ),
        migrations.AddField(
            model_name='tarjeta_flora',
            name='categoria_hambiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_flora_hambiente'),
        ),
        migrations.AddField(
            model_name='tarjeta_flora',
            name='categoria_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_flora_origen'),
        ),
        migrations.AddField(
            model_name='tarjeta_flora',
            name='categoria_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_flora_tipo'),
        ),
    ]
