# Generated by Django 5.2.8 on 2025-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0006_remove_tarjeta_fauna_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta_fauna',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='tarjeta_flora',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
