# Generated by Django 5.2.8 on 2025-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria_sobre_and_more'),
        ('tarjetas', '0007_alter_tarjeta_fauna_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_fauna',
            name='categoria_origen',
        ),
        migrations.AddField(
            model_name='tarjeta_fauna',
            name='categoria_estado',
            field=models.ManyToManyField(to='categorias.categoria_fauna_estado'),
        ),
        migrations.RemoveField(
            model_name='tarjeta_fauna',
            name='categoria_dieta',
        ),
        migrations.RemoveField(
            model_name='tarjeta_flora',
            name='categoria_hambiente',
        ),
        migrations.AddField(
            model_name='tarjeta_fauna',
            name='categoria_dieta',
            field=models.ManyToManyField(to='categorias.categoria_fauna_dieta'),
        ),
        migrations.AddField(
            model_name='tarjeta_flora',
            name='categoria_hambiente',
            field=models.ManyToManyField(to='categorias.categoria_flora_hambiente'),
        ),
    ]
