# Generated by Django 5.2.8 on 2025-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_categoria_fauna_categoria_flora'),
        ('tarjetas', '0008_remove_tarjeta_fauna_categoria_origen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_fauna',
            name='categoria_clase',
        ),
        migrations.RemoveField(
            model_name='tarjeta_fauna',
            name='categoria_dieta',
        ),
        migrations.RemoveField(
            model_name='tarjeta_fauna',
            name='categoria_estado',
        ),
        migrations.RemoveField(
            model_name='tarjeta_flora',
            name='categoria_hambiente',
        ),
        migrations.RemoveField(
            model_name='tarjeta_flora',
            name='categoria_origen',
        ),
        migrations.RemoveField(
            model_name='tarjeta_flora',
            name='categoria_tipo',
        ),
        migrations.AddField(
            model_name='tarjeta_fauna',
            name='categoria',
            field=models.ManyToManyField(to='categorias.categoria_fauna'),
        ),
        migrations.AddField(
            model_name='tarjeta_flora',
            name='categoria',
            field=models.ManyToManyField(to='categorias.categoria_flora'),
        ),
    ]
