# Generated by Django 5.2.8 on 2025-12-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_delete_categoria_fauna_clase_and_more'),
        ('tarjetas', '0009_remove_tarjeta_fauna_categoria_clase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarjeta_Flora',
            new_name='Tarjeta',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='categoria_sobre',
            field=models.ManyToManyField(to='categorias.categoria_sobre'),
        ),
        migrations.DeleteModel(
            name='Tarjeta_Fauna',
        ),
    ]
