# Generated by Django 5.2.8 on 2025-12-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0010_rename_tarjeta_flora_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='imagen',
            field=models.ImageField(upload_to='tarjetas_fotos'),
        ),
    ]
