# Generated by Django 4.2.27 on 2025-12-14 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='producto',
            new_name='post',
        ),
    ]
