# Generated by Django 5.2.8 on 2025-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=1000)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(upload_to='posts_fotos')),
            ],
        ),
    ]
