# Generated by Django 5.2.8 on 2025-12-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_categoria_sobre_post_descripcion_post_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
    ]
