# Generated by Django 5.2.8 on 2025-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria_sobre_and_more'),
        ('posts', '0004_post_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria_sobre',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria_sobre',
            field=models.ManyToManyField(to='categorias.categoria_sobre'),
        ),
    ]
