# Generated by Django 4.2.27 on 2025-12-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_categoria_sobre_post_categoria_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(default=None),
        ),
    ]
