# Generated by Django 5.2.8 on 2025-12-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('tarjetas', '0005_alter_tarjeta_fauna_nombre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria_Fauna_Diega',
            new_name='Categoria_Fauna_Dieta',
        ),
    ]
