# Generated by Django 5.2.8 on 2025-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_categoria_fauna_diega_categoria_fauna_dieta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='categoria_flora_hambiente',
            old_name='Hambiente',
            new_name='hambiente',
        ),
    ]
