# Generated by Django 5.2.8 on 2025-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria_sobre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Fauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Sin descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Sin descripción')),
            ],
        ),
    ]
