# Generated by Django 5.2.8 on 2025-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_categoria_fauna_categoria_flora'),
        ('tarjetas', '0009_remove_tarjeta_fauna_categoria_clase_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria_Fauna_Clase',
        ),
        migrations.DeleteModel(
            name='Categoria_Fauna_Dieta',
        ),
        migrations.DeleteModel(
            name='Categoria_Fauna_Estado',
        ),
        migrations.DeleteModel(
            name='Categoria_Flora_Hambiente',
        ),
        migrations.DeleteModel(
            name='Categoria_Flora_Origen',
        ),
        migrations.DeleteModel(
            name='Categoria_Flora_Tipo',
        ),
        migrations.AddField(
            model_name='categoria_sobre',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
