# Generated by Django 5.2.8 on 2025-12-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_delete_categoria_fauna_clase_and_more'),
        ('tarjetas', '0010_rename_tarjeta_flora_tarjeta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria_Fauna',
        ),
        migrations.DeleteModel(
            name='Categoria_Flora',
        ),
    ]
