# Generated by Django 5.2.8 on 2025-12-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0006_delete_categoria_fauna_delete_categoria_flora'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_sobre',
            name='imagen',
            field=models.ImageField(default=1, upload_to='categorrias_foto'),
            preserve_default=False,
        ),
    ]
