# Generated by Django 5.2.8 on 2025-12-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0007_categoria_sobre_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_sobre',
            name='imagen',
            field=models.ImageField(upload_to='categorias_foto'),
        ),
    ]
