# Generated by Django 4.2.27 on 2025-12-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0008_alter_categoria_sobre_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_sobre',
            name='descripcion',
            field=models.TextField(default=None),
        ),
    ]
